[tool.autopep8]
max_line_length = 120
ignore = "E402"
in-place = true
recursive = true
aggressive = 3

[tool.pytest.ini_options]
log_cli = 1
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
testpaths = "tests/"
